FROM golang:1.24-bookworm as build

WORKDIR /go/src/app

COPY ["go.mod", "go.sum", "./"]

RUN ["go", "mod", "download"]

COPY . .

ENV GOPROXY=https://proxy.golang.org

ENV CGO_ENABLED=0

CMD ["go", "run", "cmd/bot/main.go"]
