// Code generated by go-enum DO NOT EDIT.
// Version: 0.6.0
// Revision: 919e61c0174b91303753ee3898569a01abb32c97
// Build Date: 2023-12-18T15:54:43Z
// Built By: goreleaser

package domain

import (
	"errors"
	"fmt"
)

const (
	// SourceInstagram is a Source of type Instagram.
	SourceInstagram Source = "Instagram"
	// SourceThreads is a Source of type Threads.
	SourceThreads Source = "Threads"
)

var ErrInvalidSource = errors.New("not a valid Source")

// String implements the Stringer interface.
func (x Source) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Source) IsValid() bool {
	_, err := ParseSource(string(x))
	return err == nil
}

var _SourceValue = map[string]Source{
	"Instagram": SourceInstagram,
	"Threads":   SourceThreads,
}

// ParseSource attempts to convert a string to a Source.
func ParseSource(name string) (Source, error) {
	if x, ok := _SourceValue[name]; ok {
		return x, nil
	}
	return Source(""), fmt.Errorf("%s is %w", name, ErrInvalidSource)
}
